services:
    appverk.redactor_form_type:
        class: AppVerk\RedactorBundle\Form\Type\RedactorType
        arguments: ['@appverk.redactor_service']
        tags:
            - { name: form.type, alias: redactor }
