services:
    cube.redactor_form_type:
        class: Cube\RedactorBundle\Form\Type\RedactorType
        arguments: ['@cube.redactor_service']
        tags:
            - { name: form.type, alias: redactor }
